### ISSUE TITLE
bitcoind in init script?

### ISSUE THREAD

**Issue by bitcoinhodler** [jazarija/icecube#7]
A TODO comment in the script (above `configure_installation`) says that bitcoind should be in the init script to be executed at runtime (I assume that was supposed to say boot time). But this is not necessary, since GlacierScript will run bitcoind when appropriate.

Or are you proposing a change to this mechanism? Make bitcoind run at boot? At the very least, I would save that for rev 2 so we don't have to change `glacierscript.py` to make this work.

**Comment by jazarija** [comment]
As I understood glacierscript.py it checks whether bitcoind is already running, though I can be wrong.

I wanted to start bitcoind in advance just for the specific use cases when someone might want to play with bitcoin-cli regardless of Glacier.

If it interferes with how the script is actually structured right now, then I suggest to not start bitcoind at boot and leave it as is.

**Comment by jazarija** [comment]
Agree. Will keep bitcoind out of the way.
